name: Generate Snake Game

on:
  schedule:
    # Roda uma vez por dia à meia-noite UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    # A permissão é necessária para a nova ação de commit
    permissions:
      contents: write 
      
    runs-on: ubuntu-latest
    
    steps:
      # Passo 1: Faz o checkout do seu repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Gera a animação da cobrinha (com as opções que já tínhamos)
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          token: ${{ secrets.SNAKE_TOKEN }}
          include_private: true # Mantemos isto para garantir que vê tudo
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Passo 3: Faz o commit e push dos ficheiros gerados diretamente para a branch 'main'
      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Mensagem do commit que vai aparecer no seu histórico
          commit_message: "chore: update contribution snake animation"
          # Padrão dos ficheiros a serem guardados
          file_pattern: dist/*.svg
