name: Generate Snake Game

on:
  schedule:
    # Roda uma vez por dia à meia-noite UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Faz o checkout do seu repositório para a Action poder acessá-lo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Gera a animação da cobrinha usando o token com permissões
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          # Usa o nome de usuário do dono do repositório automaticamente
          github_user_name: ${{ github.repository_owner }}
          
          # USA O NOVO TOKEN para ler todas as contribuições públicas
          token: ${{ secrets.SNAKE_TOKEN }}
          
          # Define os arquivos de saída
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Passo 3: Envia os arquivos gerados para a branch 'output'
      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          # O GITHUB_TOKEN aqui é para dar permissão de escrita na branch, o que está correto
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}